---
- name: Generate deploy files from vars  
  hosts: Net
  connection: local
  gather_facts: no
  roles:
    - cisco.ios
  vars_files:
    - vars/{{inventory_hostname}}.yml


  tasks:
    - name: Generating Deploy Files..
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: 0777
      with_items:
        - {src: 'templates/interface-config.j2',dest: 'deploy/{{wf_ticket}}-{{inventory_hostname}}.conf'}
      delegate_to: localhost


    - name: Push Configuration to Lab
      cisco_ios:
        config_mode: "exclusive"
        load: "merge"
        src: "deploy/{{wf_ticket}}-{{inventory_hostname}}.conf"
        commit: false
      register: response
    - name: Print the complete response.
      debug:
        var: response


    - name: "Pull configs for batfish analysis"
      juniper_junos_config:
        retrieve: "committed"
        dest: "batfish-snapshots/configs/{{ inventory_hostname }}"
      register: response
    - name: Print the complete response.
      debug:
      
        var: response